[
build
]
  command = "npm run build"
  publish = "dist"

[
dev
]
  command = "npm run dev"
  framework = "astro"

# SPA fallback para Astro
[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200