[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "astro"

# Redirect for Netlify Identity
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200