# netlify.toml - Configuración corregida para Astro + Netlify CMS
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "astro"

# Configuración para Netlify Identity (sin redirección problemática)
[template.environment]
  NETLIFY_USE_EDGE_FUNCTIONS = "true"

# Redirección para el panel de administración de Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirecciones para rutas del blog (si usas routing dinámico)
[[redirects]]
  from = "/blog/*"
  to = "/blog/index.html"
  status = 200

# ELIMINAMOS la regla problemática:
# [[redirects]]
#   from = "/.netlify/identity/*"  <- ESTA LÍNEA CAUSABA EL ERROR
#   to = "/.netlify/identity/:splat"
#   status = 200

# Redirección para páginas 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"  # Cambiado para permitir Netlify CMS
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para Netlify CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com;"

# Cache para assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imágenes del blog
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"