[build]
  command = "npm install terser && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "astro"

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
