[build]
  command = "npm install terser && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "astro"

# Redirecci칩n para procesar los tokens de confirmaci칩n
[[redirects]]
  from = "/#confirmation_token=*"
  to = "/confirm/"
  status = 302
  force = true

[[redirects]]
  from = "/?confirmation_token=*"
  to = "/confirm/"
  status = 302
  force = true

# Redirecci칩n para el resto de las p치ginas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200