backend:
  name: git-gateway
  branch: main

# Configuración de medios
media_folder: "public/images/blog"
public_folder: "/images/blog"

# Workflow simple (sin drafts)
publish_mode: simple

# Configuración del sitio
site_url: https://unamorconsciente.netlify.app
display_url: https://unamorconsciente.netlify.app

# IMPORTANTE: Configuración específica para debugging
local_backend: false
show_preview_links: false

# Configuración del editor
editor:
  preview: false  # Deshabilitamos preview temporalmente

# Colección simple para testing
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} - {{author}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Fecha de publicación", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD"}
      
      # Campo de imagen simple para testing
      - label: "Imagen principal"
        name: "heroImage"
        widget: "image"
        required: false
        hint: "Sube una imagen de prueba"
      
      - label: "Autor"
        name: "author"
        widget: "select"
        options: ["Maria Magdalena Peña Romero", "Paula Prieto Peña", "Manuel Alejandro Bedoya"]
        default: "Maria Magdalena Peña Romero"
        
      - label: "Categoría"
        name: "category"
        widget: "select"
        options: ["Mindfulness", "Relaciones", "Bienestar"]
        
      - {label: "Borrador", name: "draft", widget: "boolean", default: false}
      - {label: "Contenido", name: "body", widget: "markdown"}